apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patryk
  namespace: argocd
spec:
  destination:
    namespace: patryk
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/mrdunski/argo-220908.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
